### ISSUE TITLE
auto index links

### ISSUE THREAD

**Issue by aenglert42** [TamLem/Webserv#16]
dirent struct uses char[] d_name to store dir/file-names.
We use it to create links for the auto index from it. 

problem is that non ascii chars are encoded differently by the browser and whatever is behind dirent.

e.g. ü
from dirent: u%CC%88 (would be like 'u' + '¨')
from browser: %C3%BC

For what I understand both is UTF-8 (however I'm not sure about that) and gets displayed correctly, however string or char comparison will fail (even the length will be different, because dirent uses two chars instead of one). This means that for example that I cant match locations correctly.

easiest solution: list directory content as text, not as links

**Comment by tblaase** [comment]
Since autoindexing is not really specified in the subject, I think it would be enough to show the directories as plain text

**Comment by aenglert42** [comment]
This might be the issue https://stackoverflow.com/a/6153713

**Comment by aenglert42** [comment]
Fixed it for ä, ö, ü as they are common in german, but will leave the rest.
